import NishaDeveloper from "../assets/images/png/NishaDeveloper.png";
const TeamDummyData = [
  {id:1,
    images: NishaDeveloper,
    name: "  Nisha",
    stack: "App Developer",
  },
  {id:2,
    images: NishaDeveloper,
    name: "  Nisha",
    stack: "App Developer",
  },
  {id:3,
    images: NishaDeveloper,
    name: "  Nisha",
    stack: "App Developer",
  },
  {id:4,
    images: NishaDeveloper,
    name: "  Nisha",
    stack: "App Developer",
  },
  {id:5,
    images: NishaDeveloper,
    name: "  Nisha",
    stack: "App Developer",
  },
  {id:6,
    images: NishaDeveloper,
    name: "  Nisha",
    stack: "App Developer",
  },
  {id:7,
    images: NishaDeveloper,
    name: "  Nisha",
    stack: "App Developer",
  },
  {id:8,
    images: NishaDeveloper,
    name: "  Nisha",
    stack: "App Developer",
  },
  {id:9,
    images: NishaDeveloper,
    name: "  Nisha",
    stack: "App Developer",
  },
  {id:10,
    images: NishaDeveloper,
    name: "  Nisha",
    stack: "App Developer",
  },
  {id:11,
    images: NishaDeveloper,
    name: "  Nisha",
    stack: "App Developer",
  },
  {id:12,
    images: NishaDeveloper,
    name: "  Nisha",
    stack: "App Developer",
  },
];
export default TeamDummyData;
